# Generated by Django 4.2 on 2025-04-15 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
