# Generated by Django 5.1.7 on 2025-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='terrain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
