# Generated by Django 5.1.7 on 2025-04-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.RemoveField(
            model_name='planets',
            name='updated',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='episode_nb',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='birth_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex10.planets'),
        ),
        migrations.AddField(
            model_name='people',
            name='mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='climate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='surface_water',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='terrain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
    ]
