# Generated by Django 4.2 on 2025-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_downvoted_by_tip_upvoted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_delete_tip', 'Can delete any Tip')]},
        ),
    ]
