# Generated by Django 4.2.20 on 2025-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_alter_tip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_change_password',
            field=models.BooleanField(default=True, help_text='¿Puede el usuario cambiar su contraseña?'),
        ),
    ]
