from ft_package import count_in_list

print(count_in_list(["toto", "tata", "toto"], "toto"))  # Salida: 2
print(count_in_list(["toto", "tata", "toto"], "tutu"))  # Salida: 0



"""
The files in the ft_package.egg-info/ directory contain metadata about your 
Python package. Here’s a brief explanation of the function of each:

    dependency_links.txt:
        This file is used to list dependency links for packages that are not 
        available in the Python Package Index (PyPI). However, this file is 
        not commonly used today, as most dependencies are managed directly in 
        setup.py or pyproject.toml.

    PKG-INFO:
        Contains important metadata about your package, such as its name, 
        version, author, author's email address, description, license, etc. 
        Essentially, it provides information about your package that is useful 
        for installation and distribution.

    SOURCES.txt:
        This file lists all the source files included in the package. It helps
         installers know which files need to be installed and can also be useful
         for developers who want to quickly know which files are part of the 
         package.

    top_level.txt:
        This file lists the top-level modules of the package. This includes 
        the package name and any submodule that is considered a top-level 
        module. It is useful for installation systems that need to know which
         packages and modules are available for import.

    These files are automatically generated by setuptools and provide important
    information about the package that helps manage its dependencies and 
    facilitate its installation and use.

"""