# Generated by Django 5.1.7 on 2025-04-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(blank=True, max_length=128)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('orbital_period', models.IntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('rotation_period', models.IntegerField(blank=True, null=True)),
                ('surface_water', models.FloatField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'ex08_planets',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('eye_color', models.CharField(blank=True, max_length=32)),
                ('hair_color', models.CharField(blank=True, max_length=32)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex08.planet')),
            ],
            options={
                'db_table': 'ex08_people',
            },
        ),
    ]
