# Generated by Django 4.2 on 2025-04-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_delete_tip', 'Can delete any Tip'), ('can_downvote_tip', 'Can downvote any Tip')]},
        ),
    ]
