version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ex00.d00_proyect.settings

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: djangotraining
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
