# Generated by Django 4.2.20 on 2025-05-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
