# Generated by Django 4.2.20 on 2025-04-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_tip_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote_tip', 'Can downvote a tip'), ('can_delete_tip', 'Can delete a tip')]},
        ),
    ]
