# Generated by Django 4.2.20 on 2025-05-04 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_customuser_last_password_reset_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_delete_tip', 'Puede eliminar un tip'), ('can_downvote_tip', 'Puede votar negativamente un tip')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última solicitud de restablecimiento de contraseña.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0, help_text='Reputación del usuario.'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.ForeignKey(help_text='Usuario que creó el tip.', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL, verbose_name='Votado negativamente por'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(default='Título por defecto', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL, verbose_name='Votado positivamente por'),
        ),
    ]
