# Generated by Django 4.2.20 on 2025-05-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_delete_tip', 'Can delete tip'), ('can_downvote_tip', 'Can downvote a tip')]},
        ),
    ]
