# Generated by Django 4.2.20 on 2025-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tip_title_alter_tip_author_alter_tip_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
