# Generated by Django 4.2.20 on 2025-05-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_tip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='title',
            field=models.CharField(default='Default Title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL, verbose_name='Downvoted By'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL, verbose_name='Upvoted By'),
        ),
    ]
