# Generated by Django 4.2.20 on 2025-05-11 16:29

from django.db import migrations

def create_rooms(apps, schema_editor):
    ChatRoom = apps.get_model('chat', 'ChatRoom')
    for name in ['General', 'Python', 'Random']:
        ChatRoom.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_rooms),
    ]
