# Generated by Django 5.1.7 on 2025-04-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(blank=True, max_length=255)),
                ('diameter', models.PositiveIntegerField()),
                ('orbital_period', models.PositiveIntegerField()),
                ('population', models.BigIntegerField()),
                ('rotation_period', models.PositiveIntegerField()),
                ('surface_water', models.FloatField()),
                ('terrain', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('eye_color', models.CharField(blank=True, max_length=32)),
                ('hair_color', models.CharField(blank=True, max_length=32)),
                ('height', models.PositiveIntegerField()),
                ('mass', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='ex09.planets')),
            ],
        ),
    ]
