# Generated by Django 5.1.7 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
