# Generated by Django 5.1.7 on 2025-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_alter_planets_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
