# Generated by Django 5.1.7 on 2025-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_planets_surface_water_alter_planets_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
