# Generated by Django 5.1.7 on 2025-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_alter_people_height_alter_people_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
