# Generated by Django 5.1.7 on 2025-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0006_alter_planets_rotation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
