# Generated by Django 5.1.7 on 2025-04-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0007_alter_planets_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex09.planets'),
        ),
    ]
