# Generated by Django 5.1.7 on 2025-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0008_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
