# Generated by Django 5.1.7 on 2025-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0009_alter_people_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
