# Generated by Django 5.1.7 on 2025-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0010_alter_people_eye_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
