services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: d00_project  # Nombre de la base de datos
      POSTGRES_USER: djangouser  # Usuario de la base de datos
      POSTGRES_PASSWORD: secret  # Contraseña del usuario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # Montar el proyecto local dentro del contenedor Docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: d00_project.settings # Asegúrate que esta variable esté definida aquí

volumes:
  postgres_data: