services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: d42               # Nombre de la base de datos
      POSTGRES_USER: djangouser      # Usuario de PostgreSQL
      POSTGRES_PASSWORD: secret      # Contrase침a del usuario
    ports:
      - "5432:5432"                  # Exponer el puerto 5432 para PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente para los datos
    networks:
      - django-network               # Red compartida con el servicio web

  web:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000  # Comando para iniciar el servidor Django
    volumes:
      - .:/code                      # Montar el c칩digo fuente en el contenedor
    ports:
      - "8000:8000"                  # Exponer el puerto 8000 para Django
    depends_on:
      - db                           # Asegurar que PostgreSQL se inicie antes que Django
    environment:
      DJANGO_SETTINGS_MODULE: d42.settings  # Configuraci칩n de Django
      POSTGRES_DB: d42               # Nombre de la base de datos (mismo que en db)
      POSTGRES_USER: djangouser      # Usuario de PostgreSQL (mismo que en db)
      POSTGRES_PASSWORD: secret      # Contrase침a del usuario (mismo que en db)
      POSTGRES_HOST: db              # Host de PostgreSQL (nombre del servicio db)
      POSTGRES_PORT: 5432            # Puerto de PostgreSQL (mismo que en db)
    networks:
      - django-network               # Red compartida con el servicio db

volumes:
  postgres_data:

networks:
  django-network:
    driver: bridge

